# Extract EPA's published prose for the Ragweed Pollen Season indicator and
# write it to narrative.qmd.
#
#   Rscript R/gen_narrative.R
#
# Source is data-raw/ragweed_2024 update file.docx. data-raw/ragweed_TD_2024
# update file CLEAN.docx is also vendored for provenance but not read here:
# unlike cold-related-deaths, this indicator has no supplementary figure whose
# title/caption lives only in the technical documentation. The technical
# documentation's "Table TD-1" (a station roster) is not part of EPA's
# published indicator page and is not built into data/ or narrative.qmd; see
# data-raw/PROVENANCE.md.
#
# Citations in this document are typed/Zotero-field superscript numbers
# (already display numbers 1-7, no remapping needed), not real Word endnotes.
# The document also carries 9 leftover w:endnoteReference markers from an
# earlier citation system, but every one sits inside deleted tracked-change
# content (w:del), so R/utils/read_docx.R correctly excludes all of them from
# the rendered text; nothing here needs to special-case them.

root <- here::here()
source(file.path(root, "R", "utils", "read_docx.R"))
source(file.path(root, "R", "utils", "write_stable.R"))

raw_dir   <- file.path(root, "data-raw")
TEXT_DOCX <- file.path(raw_dir, "ragweed_2024 update file.docx")
OUT_QMD   <- file.path(root, "narrative.qmd")

if (!file.exists(TEXT_DOCX)) {
  stop("Source document not found: ", TEXT_DOCX, call. = FALSE)
}

df  <- read_docx_paragraphs(TEXT_DOCX)
sec <- docx_sections(df)

get <- function(rng) paste(df$text_md[rng], collapse = "\n\n")

title    <- df$text_plain[1]
subtitle <- df$text_plain[2]

# Key Points is a bulleted list; the section's raw paragraph range also
# contains the Figure 1 title/caption/source block that Word placed after the
# bullets and before "Indicator Notes", so bullets are selected by style
# within that range rather than by taking the whole range verbatim. Figure
# 1's own title/data source/web update already live in data/meta.yml (read
# from the CSV's own preamble in R/build_data.R), so they are not duplicated
# here.
kp_idx     <- sec[["Key Points"]]
key_points <- df$text_md[kp_idx][df$style[kp_idx] == "Bullet2" & !df$empty[kp_idx]]

background          <- get(sec[["Background"]])
about_the_indicator <- get(sec[["About the Indicator"]])
indicator_notes      <- get(sec[["Indicator Notes"]])
data_sources         <- get(sec[["Data Sources"]])

# References: numbers are already 1:7 in document order.
references_idx <- sec[["References"]]
references_idx <- references_idx[!df$empty[references_idx]]
references_raw <- df$text_md[references_idx]
ref_num  <- as.integer(sub("^(\\d{1,2})\\..*$", "\\1", references_raw))
stopifnot("reference numbers are not 1:7 in order" = identical(ref_num, 1:7))
ref_text <- sub("^\\d{1,2}\\.\\s*", "", references_raw)
references_html <- paste0(
  '<ol class="references">\n',
  paste0('  <li id="ref-', ref_num, '">', ref_text, "</li>", collapse = "\n"),
  "\n</ol>"
)

# Body superscript reference markers, e.g. "^5,6^", become links to those
# anchors: "[5](#ref-5),[6](#ref-6)" wrapped back in superscript markup.
sup_to_links <- function(x) {
  m <- gregexpr("\\^[0-9,]+\\^", x)
  regmatches(x, m) <- lapply(regmatches(x, m), function(hits) {
    vapply(hits, function(h) {
      nums <- strsplit(sub("^\\^", "", sub("\\^$", "", h)), ",")[[1]]
      linked <- paste0("[", nums, "](#ref-", nums, ")", collapse = ",")
      paste0("^", linked, "^")
    }, character(1))
  })
  x
}
background           <- sup_to_links(background)
about_the_indicator   <- sup_to_links(about_the_indicator)
key_points            <- sup_to_links(key_points)
indicator_notes       <- sup_to_links(indicator_notes)
data_sources          <- sup_to_links(data_sources)

out <- c(
  "---",
  paste0('title: "', title, '"'),
  paste0('subtitle: "', subtitle, '"'),
  "---",
  "",
  "<!-- Generated by R/gen_narrative.R from data-raw/ragweed_2024 update file.docx.",
  "     Do not edit by hand: rerunning the generator overwrites this file. -->",
  "",
  "## Key Points", "",
  paste0("- ", key_points, collapse = "\n\n"), "",
  "## Background", "",
  background, "",
  "## About the Indicator", "",
  about_the_indicator, "",
  "## Indicator Notes", "",
  indicator_notes, "",
  "## Data Sources", "",
  data_sources, "",
  "## References", "",
  references_html, ""
)

write_lines_stable(out, OUT_QMD)
assert_clean_output(OUT_QMD)

cat("Wrote", basename(OUT_QMD), "-", length(out), "lines,",
    length(ref_num), "references.\n")
